# PowerShell script to dump the PostgreSQL database
# generated by dev.py on Wed Nov 13 16:08:33 2024
# Edit the generated values per your actual deployments.

$server=$Env:AIG4PG_PG_FLEX_SERVER
$port=$Env:AIG4PG_PG_FLEX_PORT
$user=$Env:AIG4PG_PG_FLEX_USER
$db='dev'
$table='libraries2'

if (-not (Test-Path -Path .\tmp\dump)) {
 New-Item -ItemType Directory -Path .\tmp\dump
}
Set-Clipboard -value $Env:AIG4PG_PG_FLEX_PASS

Write-Host 'dumping the --schema-only, enter password...'
pg_dump --schema-only --host $server --port $port --username $user --format plain --verbose --file 'tmp\dump\pg_dump_libraries_schema.sql' --dbname $db --table $table 

Write-Host 'dumping the --data-only, enter password...'
pg_dump --data-only --host $server --port $port --username $user --format plain --verbose --file 'tmp\dump\pg_dump_libraries_data.sql' --dbname $db --table $table 

Set-Clipboard -value 'done'

Write-Host 'list of tmp\dump files:'
Get-ChildItem tmp\dump

